### ISSUE TITLE
JavaScript config instructions are Webpack-specific and do not work with esbuild

### ISSUE THREAD

**Issue by unikitty37** [ViewComponent/view_component#1409]
When using esbuild rather than webpack, following the instructions for configuring JavaScript does not work as the example given is Webpack-specific.

### Steps to reproduce
* Create a project with `rails new -j esbuild app`
* Add `view_component` to the Gemfile and run `bundle install`
* `rails g component Thingy`
* Create app/components/thingy_component.js, containing just `console.log('IT WORKS')`
* Add the following as app/javascripts/components.js, as per https://viewcomponent.org/guide/javascript_and_css.html

```js
function importAll(r) {
  r.keys().forEach(r)
}

importAll(require.context("../components", true, /[_\/]component\.js$/))
```
* Add `import './components'` to app/javascript/application.js
* Run `rails server` and visit http://localhost:3000

### Expected behaviour

The browser console should contain "IT WORKS" and no errors.

### Actual behaviour

The browser console does not contain "IT WORKS", but has the error

```
components.js:7 Uncaught TypeError: __require.context is not a function
    at components.js:7:19
    at components.js:7:72
```

It appears `require.context` is Webpack-specific. It would help if there could be instructions for all the Javascript systems supported by Rails 7 — or, at least, if the code could be something generic that doesn't require a specific bundling system.

Changing `require.context` to `require` produces this error instead:

```
Uncaught Error: Dynamic require of "../components" is not supported
    at application-55e5e85f5c0e2bd2aa3dc0c7b2a654c8c3b42ce5d1a57fd9e1ecc63897b1b50f.js:9:11
    at components.js:7:11
    at components.js:7:64
```

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3,1,2

**Gem version**: 2.57.1 (or 3.3.16 if you actually wanted the output of `gem --version` — it's not 100% clear :)

**Comment by unikitty37** [comment]
I've since given up on esbuild due to other limitations, and moved to webpack, so this isn't affecting me any more. I'll leave this open if you don't mind, as I still think the docs could use instructions for the other JS build systems Rails supports.

**Comment by Spone** [comment]
Yes, we're currently looking into this. We'll probably add instructions for this use case to the docs.

**Comment by yorsant** [comment]
Any update on this issue?

**Comment by sncalvo** [comment]
Just checking, but any updates on this issue?

**Comment by joelhawksley** [comment]
No updates from what I can tell. 

I'd welcome a community contribution here: ViewComponent does not have any interaction with assets as it is designed, but we provide these kinds of guides on a best-effort basis to share what approaches have worked for others.

**Comment by Spone** [comment]
I think a good step forward would be preparing a list of the various setups that we want to document.

I'll start with two setups I'm familiar with and can provide instructions for:
- ViewComponent, Webpacker, Stimulus and PostCSS
- ViewComponent, esbuild, Stimulus, PostCSS with postcss-modules for CSS "encapsulation"/namespacing

I'd be interested in learning more about setups with jsbundling / cssbundling, propshaft, importmaps.

Then I think the easiest starting point would be to write a couple sample components and provide reference demo apps implementing these various approaches, as GitHub repositories.

Feel free to reply with your own working setups!

**Comment by sncalvo** [comment]
I figured out the ESBuild case using `esbuild-rails` plugin.
It adds support for glob imports.

With stimulus controller, my setup looks like this:
```js
import componentControllers from '../../components/**/*_controller.js';

componentControllers.forEach((controller) => {
  application.register(controller.name, controller.module.default)
});
```

It can probably be improved by adding aliases to the components instead of using a relative path.

**Comment by sncalvo** [comment]
@Spone, reach out if you think I can be of assistance!

**Comment by joelhawksley** [comment]
Closing as stale.
