### ISSUE TITLE
undefined method `filtered_parameters' for nil:NilClass

### ISSUE THREAD

**Issue by jcoyne** [ViewComponent/view_component#1685]
This commit 0a7a3721b4f7d481b76c43efa4e9a676833da88b  breaks my test because the view_context for the controller returns nil when `request` is called.

```
     NoMethodError:
       undefined method `filtered_parameters' for nil:NilClass

                 params: request.filtered_parameters
                                ^^^^^^^^^^^^^^^^^^^^
     # /Users/jcoyne85/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_controller/metal/strong_parameters.rb:1230:in `params'
     # /Users/jcoyne85/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/actionview-7.0.4.3/lib/action_view/helpers/controller_helper.rb:16:in `params'
     # ./app/helpers/blacklight/catalog_helper_behavior.rb:199:in `document_index_view_type'
     # ./app/helpers/blacklight/document_helper_behavior.rb:73:in `document_presenter_class'
     # ./app/helpers/blacklight/document_helper_behavior.rb:62:in `document_presenter'
     # ./spec/components/blacklight/document_component_spec.rb:18:in `block (2 levels) in <top (required)>'
```

You can observe this by calling
`controller.view_context.params`

in a component test, which results in:
```
eval error: undefined method `filtered_parameters' for nil:NilClass

          params: request.filtered_parameters
                         ^^^^^^^^^^^^^^^^^^^^
```

**Comment by jcoyne** [comment]
Sorry, this was because we were coding against the private method from rc2.  Switching to use the new method name fixes it. Thank you.
