### ISSUE TITLE
`render_component` not available in a component's view template (`.html.erb`)?

### ISSUE THREAD

**Issue by fredboyle** [ViewComponent/view_component#1800]
### Steps to reproduce

- Add `config.view_component.render_monkey_patch_enabled = false` to your app's config
- Create a new component to be consumed within another
- In the "parent" component's view template add: `<%= render_component(ChildComponent.new()) %>`
- Try to load the preview

### Expected behavior
Component should render without issue.

### Actual behavior
Error of: undefined method `render_component` occurs.

### Additional notes
`render_component` functions without issue in other locations such as the preview definitions.

**Backtrace**:
```
Full stack trace:

/Users/FredBoyle/Documents/_Code/Zest/zest-rails-engine/app/components/zest/checkbox_group_component/checkbox_group_component.html.erb:6:in `block in call'
/Users/FredBoyle/Documents/_Code/Zest/zest-rails-engine/app/components/zest/checkbox_group_component/checkbox_group_component.html.erb:5:in `each'
/Users/FredBoyle/Documents/_Code/Zest/zest-rails-engine/app/components/zest/checkbox_group_component/checkbox_group_component.html.erb:5:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/view_component-3.2.0/lib/view_component/compiler.rb:115:in `render_template_for'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/view_component-3.2.0/lib/view_component/base.rb:108:in `render_in'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/helpers/rendering_helper.rb:42:in `render'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/view_component-3.2.0/app/views/view_components/preview.html.erb:3:in `___sers__red_oyle__gem_ruby_______gems_view_component_______app_views_view_components_preview_html_erb__3806173277395246519_354280'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/base.rb:244:in `public_send'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/base.rb:244:in `_run'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/template.rb:157:in `block in render'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/notifications.rb:208:in `instrument'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/template.rb:361:in `instrument_render_template'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/template.rb:155:in `render'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `instrument'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/renderer/template_renderer.rb:79:in `render_with_layout'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/renderer/template_renderer.rb:59:in `render_template'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/renderer/template_renderer.rb:11:in `render'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/rendering.rb:117:in `block in _render_template'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/base.rb:270:in `in_rendering_context'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/rendering.rb:116:in `_render_template'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/streaming.rb:216:in `_render_template'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/rendering.rb:103:in `render_to_body'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/rendering.rb:158:in `render_to_body'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/renderers.rb:141:in `render_to_body'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/abstract_controller/rendering.rb:45:in `render_to_string'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/rendering.rb:147:in `render_to_string'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/lookbook-2.0.5/lib/lookbook/preview_controller_actions.rb:23:in `render_scenario_to_string'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/abstract_controller/base.rb:215:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/rendering.rb:165:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actiontext-7.0.5/lib/action_text/rendering.rb:20:in `with_renderer'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actiontext-7.0.5/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `instance_exec'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:138:in `run_callbacks'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/abstract_controller/callbacks.rb:233:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/rescue.rb:22:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `instrument'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activerecord-7.0.5/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/abstract_controller/base.rb:151:in `process'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/rendering.rb:39:in `process'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/lookbook-2.0.5/app/controllers/concerns/lookbook/targetable_concern.rb:99:in `block in inspector_data'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/lookbook-2.0.5/app/controllers/concerns/lookbook/targetable_concern.rb:98:in `map'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/lookbook-2.0.5/app/controllers/concerns/lookbook/targetable_concern.rb:98:in `inspector_data'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/lookbook-2.0.5/app/controllers/concerns/lookbook/with_panels_concern.rb:18:in `block in main_panels'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/lookbook-2.0.5/app/controllers/concerns/lookbook/with_panels_concern.rb:17:in `map'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/lookbook-2.0.5/app/controllers/concerns/lookbook/with_panels_concern.rb:17:in `main_panels'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/lookbook-2.0.5/app/controllers/lookbook/inspector_controller.rb:14:in `show'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/abstract_controller/base.rb:215:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/rendering.rb:165:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actiontext-7.0.5/lib/action_text/rendering.rb:20:in `with_renderer'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actiontext-7.0.5/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `instance_exec'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:138:in `run_callbacks'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/abstract_controller/callbacks.rb:233:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/rescue.rb:22:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `instrument'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activerecord-7.0.5/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/abstract_controller/base.rb:151:in `process'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionview-7.0.5/lib/action_view/rendering.rb:39:in `process'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal.rb:188:in `dispatch'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_controller/metal.rb:251:in `dispatch'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/journey/router.rb:32:in `each'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/journey/router.rb:32:in `serve'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/routing/route_set.rb:852:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/railties-7.0.5/lib/rails/engine.rb:530:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/railties-7.0.5/lib/rails/railtie.rb:226:in `public_send'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/railties-7.0.5/lib/rails/railtie.rb:226:in `method_missing'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/journey/router.rb:32:in `each'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/journey/router.rb:32:in `serve'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/routing/route_set.rb:852:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/static.rb:23:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/rack-2.2.7/lib/rack/static.rb:161:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/rack-2.2.7/lib/rack/tempfile_reaper.rb:15:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/rack-2.2.7/lib/rack/etag.rb:27:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/rack-2.2.7/lib/rack/conditional_get.rb:27:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/rack-2.2.7/lib/rack/head.rb:12:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/rack-2.2.7/lib/rack/session/abstract/id.rb:266:in `context'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/rack-2.2.7/lib/rack/session/abstract/id.rb:260:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/cookies.rb:704:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activerecord-7.0.5/lib/active_record/migration.rb:603:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:99:in `run_callbacks'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/railties-7.0.5/lib/rails/rack/logger.rb:40:in `call_app'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/railties-7.0.5/lib/rails/rack/logger.rb:25:in `block in call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:37:in `tagged'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:99:in `tagged'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/railties-7.0.5/lib/rails/rack/logger.rb:25:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/rack-2.2.7/lib/rack/method_override.rb:24:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/rack-2.2.7/lib/rack/runtime.rb:22:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/activesupport-7.0.5/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/server_timing.rb:60:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/static.rb:23:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/rack-2.2.7/lib/rack/sendfile.rb:110:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/actionpack-7.0.5/lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/railties-7.0.5/lib/rails/engine.rb:530:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/puma-6.3.0/lib/puma/configuration.rb:270:in `call'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/puma-6.3.0/lib/puma/request.rb:100:in `block in handle_request'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/puma-6.3.0/lib/puma/thread_pool.rb:344:in `with_force_shutdown'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/puma-6.3.0/lib/puma/request.rb:99:in `handle_request'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/puma-6.3.0/lib/puma/server.rb:443:in `process_client'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/puma-6.3.0/lib/puma/server.rb:245:in `block in run'
/Users/FredBoyle/.gem/ruby/3.2.2/gems/puma-6.3.0/lib/puma/thread_pool.rb:151:in `block in spawn_thread'
```

### System configuration
**Rails version**:
7.0.5

**Ruby version**:
3.2.2

**Gem version**:
3.2.0

**Comment by camertron** [comment]
Hey @fredboyle, `#render_component` isn't included if you're running Rails >= 6.1. Are you able to call `#render` instead?

**Comment by fredboyle** [comment]
@camertron Yes, using `render` functions as expected but it feels odd that `render_component` is accessible everywhere else but not there. `render_component` also feels significantly clearer when needing to output a ViewComponent.

Lastly this is actually a Rails Engine library of components that will be consumed by a pre Rails 6.1 environment so we want to ensure that there won't be any `stack level too deep` issues due to other gems in use, such as "wicked_pdf".

Any guidance is appreciated, whether `render` is safe and just what we have to use or if there's a way to enable `render_component` to always be available.

**Comment by camertron** [comment]
> it feels odd that `render_component` is accessible everywhere else but not there

Can you clarify what you mean by "everywhere else"? The `#render_component` method should not be available anywhere unless you're running Rails < 6.1. Are you saying it's not available in the component's view template under Rails < 6.1? The stack trace you included seems to indicate you're running Rails 7.0.5.

> Lastly this is actually a Rails Engine library of components that will be consumed by a pre Rails 6.1 environment.

Ah ok, that makes sense. Is there some reason you're disabling the render monkey patch? Leaving it in means you can rely on `#render` for any version of Rails that ViewComponent supports.

If you're (understandably) leery of monkey patches, it might help to know that `#render_component` is also added via a series of monkey patches, albeit ones that do not override existing methods. If you really want to use `#render_component` instead of `#render`, you can always replicate what ViewComponent's engine does by adding this to an initializer in your lib's engine:

```ruby
ActiveSupport.on_load(:action_view) do
  require "view_component/render_monkey_patch"
  ActionView::Base.prepend ViewComponent::RenderMonkeyPatch
end

ActiveSupport.on_load(:action_controller) do
  require "view_component/rendering_monkey_patch"
  require "view_component/render_to_string_monkey_patch"
  ActionController::Base.prepend ViewComponent::RenderingMonkeyPatch
  ActionController::Base.prepend ViewComponent::RenderToStringMonkeyPatch
end
```

You'll probably want to do that only if `Rails.version.to_f < 6.1`.

**Comment by fredboyle** [comment]
@camertron Thanks for the explanation and additional details.

The `render_component` is available to us in the various component preview files and in the app consuming the gem.

The primary reason is that there are gems in the consuming app that also monkey patch `render` and with the addition of ViewComponent end up creating "stack level too deep" errors in most of our app. So removing the monkey patch and relying on a more explicit `render_component` makes sense, separates concerns, and removes the issue.

So it sounds like we'll need to do a bit of testing to see if `render` in our component views/templates breaks anything in the consuming app, and if so follow your recommendation of the added code to an initializer.

**Comment by rmacklin** [comment]
@camertron Is adding all of that necessary if they just want to use `render_component` (and _not_ use `render`)? If that's what's desired, wouldn't the code to add be:
```rb
ActiveSupport.on_load(:action_view) do
  require "view_component/render_component_helper"
  ActionView::Base.include ViewComponent::RenderComponentHelper
end
```
?

**Comment by camertron** [comment]
Woops, right you are @rmacklin. I'll edit my comment.

**Comment by rmacklin** [comment]
Hmm, I'm still not sure it'd be required to add `RenderMonkeyPatch` if they only want to use `render_component` 🤔

**Comment by fredboyle** [comment]
A quick update that testing with a Rails 5.2 app consuming the gem does not function if the ViewComponent monkey patch config value is set to false. Changing the component's view to use `render_component`, instead of `render`, functions as expected. However the side effect is that our Lookbook installation for development that runs from the gem scope then breaks for that component.

It appears we'll need to add the monkey patch in per your suggestion in order for things to function across all environments.

Please let me know if you feel this might cause issues in the long-term or may break in future versions of ViewComponent. Thanks again for the assistance.

**Comment by camertron** [comment]
> The `render_component` is available to us in the various component preview files and in the app consuming the gem.

Do the preview files also live in the app?

> The primary reason is that there are gems in the consuming app that also monkey patch `render`

Ah ok 👍 

> So removing the monkey patch and relying on a more explicit render_component makes sense, separates concerns, and removes the issue.

Yeah that makes sense. Sounds like `#render_component` is the way to go in your case. Let me know if the `include` above works as expected.

**Comment by camertron** [comment]
@rmacklin in order to be able to use `#render_component` everywhere, including older _and_ newer Rails apps, I think that `include` is still necessary. AFAIK `#render_component` isn't defined anywhere except in ViewComponent.

**Comment by rmacklin** [comment]
Yeah, my confusion is that `render_component` is defined in `ViewComponent::RenderComponentHelper`, not `ViewComponent::RenderMonkeyPatch`

**Comment by camertron** [comment]
@rmacklin 🤦 right, my mistake. Comment updated!

**Comment by fredboyle** [comment]
Quick initial testing shows that the suggestion from @rmacklin does the trick both in the gem/engine's environment with Lookbook as well as a consuming Rails 5.2 app. So it enables the use of `render_component` in both environments.

**Comment by camertron** [comment]
Sounds like this has been resolved @fredboyle. Feel free to re-open if you still have questions.
