### ISSUE TITLE
`ViewComponent::Base.view_component_path` defaulting to `nil` breaks `rails stats`

### ISSUE THREAD

**Issue by rspeicher** [ViewComponent/view_component#1804]
### Steps to reproduce

```sh
$ rails new --skip-bundle view_component_test
$ cd view_component_test
$ bundle add view_component
$ bundle exec rails stats
```

### Expected behavior

Rails show should stats, including code for View Components.

### Actual behavior

```sh
$ bundle exec rails stats
rails aborted!
TypeError: no implicit conversion of nil into String

Tasks: TOP => stats
(See full trace by running task with --trace)
```

This is a result of `STATS_DIRECTORIES` containing `["ViewComponents", nil]`, which gets added [here](https://github.com/ViewComponent/view_component/blob/095f76f7140260402741293716d8a7472c0d9e4a/lib/view_component/rails/tasks/view_component.rake#L10).

**Backtrace**:

```
<internal:dir>:98:in `open'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/code_statistics.rb:46:in `foreach'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/code_statistics.rb:46:in `calculate_directory_statistics'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/code_statistics.rb:40:in `block in calculate_statistics'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/code_statistics.rb:40:in `map'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/code_statistics.rb:40:in `calculate_statistics'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/code_statistics.rb:21:in `initialize'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/tasks/statistics.rake:36:in `new'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/tasks/statistics.rake:36:in `block in <main>'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/command.rb:51:in `invoke'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.6/lib/rails/commands.rb:18:in `<main>'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => stats
```

### System configuration
**Rails version**: 7.0.6

**Ruby version**: 3.2.0

**Gem version**: 3.4.0

**Comment by boardfish** [comment]
Hey @rspeicher, thanks for raising this! I'd hazard a guess that #1774 will fix this issue, since it'll initialize a config object instead of a blank `OrderedOptions` – could you try that branch and see if it solves the problem?

**Comment by rspeicher** [comment]
@boardfish Looks good! 👍🏻 

```sh
$ bundle show view_component
/Users/rspeicher/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/bundler/gems/view_component-e4268dc9c172

$ bin/rails stats
rails aborted!
Errno::ENOENT: No such file or directory @ dir_initialize - app/components

Tasks: TOP => stats
(See full trace by running task with --trace)

$ mkdir app/components

$ bin/rails stats
+----------------------+--------+--------+---------+---------+-----+-------+
| Name                 |  Lines |    LOC | Classes | Methods | M/C | LOC/M |
+----------------------+--------+--------+---------+---------+-----+-------+
| Controllers          |      2 |      2 |       1 |       0 |   0 |     0 |
| Helpers              |      2 |      2 |       0 |       0 |   0 |     0 |
| Jobs                 |      7 |      2 |       1 |       0 |   0 |     0 |
| Models               |      3 |      3 |       1 |       0 |   0 |     0 |
| Mailers              |      4 |      4 |       1 |       0 |   0 |     0 |
| Channels             |      8 |      8 |       2 |       0 |   0 |     0 |
| Views                |     29 |     26 |       0 |       0 |   0 |     0 |
| Stylesheets          |     15 |     15 |       0 |       0 |   0 |     0 |
| Libraries            |      0 |      0 |       0 |       0 |   0 |     0 |
| Controller tests     |      0 |      0 |       0 |       0 |   0 |     0 |
| Helper tests         |      0 |      0 |       0 |       0 |   0 |     0 |
| Model tests          |      0 |      0 |       0 |       0 |   0 |     0 |
| Mailer tests         |      0 |      0 |       0 |       0 |   0 |     0 |
| Channel tests        |     11 |      3 |       1 |       0 |   0 |     0 |
| Integration tests    |      0 |      0 |       0 |       0 |   0 |     0 |
| System tests         |      0 |      0 |       0 |       0 |   0 |     0 |
| ViewComponents       |      0 |      0 |       0 |       0 |   0 |     0 |
+----------------------+--------+--------+---------+---------+-----+-------+
| Total                |     81 |     65 |       7 |       0 |   0 |     0 |
+----------------------+--------+--------+---------+---------+-----+-------+
  Code LOC: 62     Test LOC: 3     Code to Test Ratio: 1:0.0
```
