### ISSUE TITLE
bug: Slots with names that start with the characters `call` raise an exception

### ISSUE THREAD

**Issue by wenley** [ViewComponent/view_component#1825]
### Steps to reproduce

1. Define a ViewComponent with a `renders_one` slot
2. Name the slot with the `call` prefix (e.g. `callout_action`)
3. Use the new component in a template (i.e. `render(NewComponent.new(...))`). It does not matter whether the slot is used or not.
4. Load the page that uses the new component

### Expected behavior
The page should render.

### Actual behavior
A `NameError` "undefined method" exception is thrown, causing the page to fail to load.

Here is a PR with a failing test: https://github.com/ViewComponent/view_component/pull/1821

**Backtrace** (from [this PR CI run](https://github.com/ViewComponent/view_component/actions/runs/5872234737/job/15923396689?pr=1821)):
```
/home/runner/work/view_component/view_component/lib/view_component/compiler.rb:99:in `instance_method': undefined method `call_callout_title' for class `EmptySlotComponent' (NameError)
	from /home/runner/work/view_component/view_component/lib/view_component/compiler.rb:99:in `block in define_render_template_for'
	from /home/runner/work/view_component/view_component/lib/view_component/compiler.rb:97:in `map'
	from /home/runner/work/view_component/view_component/lib/view_component/compiler.rb:97:in `define_render_template_for'
	from /home/runner/work/view_component/view_component/lib/view_component/compiler.rb:84:in `compile'
	from /home/runner/work/view_component/view_component/lib/view_component/base.rb:512:in `compile'
	from /home/runner/work/view_component/view_component/lib/view_component/engine.rb:75:in `each'
	from /home/runner/work/view_component/view_component/lib/view_component/engine.rb:75:in `block (2 levels) in <class:Engine>'
	from /home/runner/work/view_component/view_component/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
	from /home/runner/work/view_component/view_component/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	from /home/runner/work/view_component/view_component/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
	from /home/runner/work/view_component/view_component/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
	from /home/runner/work/view_component/view_component/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	from /home/runner/work/view_component/view_component/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:51:in `each'
	from /home/runner/work/view_component/view_component/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	from /home/runner/work/view_component/view_component/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
	from /home/runner/work/view_component/view_component/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/runner/work/view_component/view_component/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `run'
	from /home/runner/work/view_component/view_component/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:61:in `block in run_initializers'
```

Here is also a full Rails app that can be run locally to demonstrate the error: https://github.com/wenley/ViewComponent-3.5.0-bug

### System configuration
**Rails version**: 7.0.7

**Ruby version**: 3.2.2

**Gem version**: 3.5.0

**Comment by Spone** [comment]
Thanks for the detailed bug report! We're open to contributions that fix the issue.
