### ISSUE TITLE
undefined method `strftime' for nil:NilClass with nil datetime

### ISSUE THREAD

**Issue by xdmx** [ViewComponent/view_component#1842]
### Steps to reproduce

```
  # @param next_payment_at datetime-local
  def default(next_payment_at: nil)
    render(Pages::BillingComponent.new(next_payment_at:))
  end
```

### Expected behavior

The default `nil` value should work

### Actual behavior

Error page with `undefined method 'strftime' for nil:NilClass`

**Backtrace**:
```

/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/lookbook-2.0.5/lib/lookbook/param.rb:31:in `value'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/lookbook-2.0.5/app/components/lookbook/params/field/component.rb:34:in `render_input'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/lookbook-2.0.5/app/components/lookbook/params/field/component.rb:14:in `before_render'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.5.0/lib/view_component/base.rb:107:in `render_in'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.5.0/lib/view_component/slot.rb:62:in `to_s'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.7.2/lib/active_support/core_ext/string/output_safety.rb:42:in `unwrapped_html_escape'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.7.2/lib/action_view/helpers/output_safety_helper.rb:36:in `block in safe_join'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.7.2/lib/action_view/helpers/output_safety_helper.rb:36:in `map!'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.7.2/lib/action_view/helpers/output_safety_helper.rb:36:in `safe_join'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/lookbook-2.0.5/app/components/lookbook/params/editor/component.html.erb:12:in `block in call'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.7.2/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.7.2/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.7.2/lib/action_view/helpers/capture_helper.rb:45:in `capture'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.5.0/lib/view_component/base.rb:263:in `content'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/lookbook-2.0.5/app/components/lookbook/tag_component.rb:18:in `block in call'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.7.2/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.7.2/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.7.2/lib/action_view/helpers/capture_helper.rb:45:in `capture'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.7.2/lib/action_view/helpers/tag_helper.rb:71:in `tag_string'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.7.2/lib/action_view/helpers/tag_helper.rb:189:in `method_missing'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/lookbook-2.0.5/app/components/lookbook/tag_component.rb:17:in `public_send'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/lookbook-2.0.5/app/components/lookbook/tag_component.rb:17:in `call'
/home/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.5.0/lib/view_component/compiler.rb:120:in `render_template_for' 
```

### System configuration
**Rails version**: 7.0

**Ruby version**: 3.2

**Gem version**: 3.5

**Comment by camertron** [comment]
Hey @xdmx, it's difficult to diagnose this issue without a more complete example. Can you provide a test app for us to take a look at?

**Comment by xdmx** [comment]
My bad :man_facepalming: this relates to lookbook, not viewcomponent. Sorry for the noise!
