### ISSUE TITLE
Components with only variant template crashes the app

### ISSUE THREAD

**Issue by sigra** [ViewComponent/view_component#1956]
I've started to upgrade from 3.2.0 to 3.9.0 and my application stopped launching. Downgrading version by version I found that the issue starts from [3.5.0](https://github.com/ViewComponent/view_component/compare/v3.4.0...v3.5.0).

The app crashes with the error like:

```
NameError:
  undefined method `call' for class `ExampleComponent'
```

My component doesn't have template without variant and I sure it's an issue. Seems that `Compiler#define_render_template_for` expects that component class always has `:call` method defined:

https://github.com/ViewComponent/view_component/blob/3487283035bbcb868e46f93fcfb6abadfeed650a/lib/view_component/compiler.rb#L104

But this method isn't defined because my component has only "variant" template:

https://github.com/ViewComponent/view_component/blob/3487283035bbcb868e46f93fcfb6abadfeed650a/lib/view_component/compiler.rb#L69-L82

### Steps to reproduce
1) Make a component using [subdirectory](https://viewcomponent.org/guide/templates.html#subdirectory) template structure

```
app/components
├── ...
├── example_component.rb
├── example_component
|   ├── example_component.html+table.haml
├── ...
```

2) Run the app

### System configuration
**Rails version**:
6.1.7.5

**Ruby version**:
3.2.2

**Gem version**:
3.5.0

**Comment by reeganviljoen** [comment]
@sigra I will take a look into this and either provide a fix or ping someone that can

**Comment by boardfish** [comment]
Thanks for the diagnosis, @reeganviljoen! Knowing this, we could start returning a helpful error here with similar advice to what you've provided just there.

**Comment by reeganviljoen** [comment]
@boardfish I can get that working when I get some time

**Comment by sigra** [comment]
Thanks for reply, @reeganviljoen . Patching the `render?` method didn't help. Because the error occurs earlier in the `inherited` block where `compile` method is called.

```ruby
class ExampleComponent < ApplicationComponent
  def render?
    raise 'Unreachable code'
  end
end
```

Rails console output:

```
irb(main):001:0> ExampleComponent
/Users/sigra/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.9.0/lib/view_component/compiler.rb:110:in `instance_method': undefined method `call' for class `ExampleComponent' (NameError)

      component_class.define_method(:"_call_#{safe_class_name}", component_class.instance_method(:call))
                                                                                ^^^^^^^^^^^^^^^^
Did you mean?  caller
```

Backtrace:

```
.../view_component-3.9.0/lib/view_component/compiler.rb:111:in `instance_method'
.../view_component-3.9.0/lib/view_component/compiler.rb:111:in `define_render_template_for'
.../view_component-3.9.0/lib/view_component/compiler.rb:86:in `compile'
.../view_component-3.9.0/lib/view_component/base.rb:562:in `compile'
.../view_component-3.9.0/lib/view_component/base.rb:497:in `inherited'
```

I know that I can create empty `example_component.haml.html` template and it will fix the problem. But as for me it's a little bit hacky way, because my app doesn't need to have this template. So, I assume it's a bug.

As for me the most obvious way is to check is method `call` defined or not by using the `call_defined?` method.

https://github.com/ViewComponent/view_component/blob/c8462c2113ca1771b681fc89eb025d8e8b685727/lib/view_component/compiler.rb#L300-L303

Suggested fix:

```ruby
      if call_defined?
        component_class.define_method(:"_call_#{safe_class_name}", component_class.instance_method(:call))
      end
```

**Comment by reeganviljoen** [comment]
@sigra we really appreciate your debug samples and reproduction, this will certainly help, would you be able to write a failing test for this situation so someone can use that as a guideline to fix this bug ?

**Comment by sigra** [comment]
@reeganviljoen will be it enough? https://github.com/sigra/view_component/commit/0b8053980e73bf5302881b487cbaaa6dd8d98e36

```
➜  view_component git:(main) ✗ bundle exec appraisal rake

>> BUNDLE_GEMFILE=/Users/sigra/projects/view_component/gemfiles/rails_6.1.gemfile bundle exec rake
/Users/sigra/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-6.1.7.6/lib/active_support/core_ext/class/subclasses.rb:30: warning: method redefined; discarding old subclasses
/Users/sigra/projects/view_component/lib/view_component/compiler.rb:110:in `instance_method': undefined method `call' for class `VariantComponentWithoutDefaultTemplate' (NameError)

      component_class.define_method(:"_call_#{safe_class_name}", component_class.instance_method(:call))
                                                                                ^^^^^^^^^^^^^^^^
Did you mean?  caller
	from /Users/sigra/projects/view_component/lib/view_component/compiler.rb:110:in `define_render_template_for'
	from /Users/sigra/projects/view_component/lib/view_component/compiler.rb:86:in `compile'
	from /Users/sigra/projects/view_component/lib/view_component/base.rb:577:in `compile'
	from /Users/sigra/projects/view_component/lib/view_component/engine.rb:76:in `each'
	from /Users/sigra/projects/view_component/lib/view_component/engine.rb:76:in `block (2 levels) in <class:Engine>'
```

**Comment by reeganviljoen** [comment]
@sigra this is a bug helpbthank you

**Comment by joelhawksley** [comment]
Verified as no longer an issue in `v4`: https://github.com/ViewComponent/view_component/pull/2323
