### ISSUE TITLE
v3.9.0 security fix assumes request will have format

### ISSUE THREAD

**Issue by boardfish** [ViewComponent/view_component#1968]
### Steps to reproduce

Set up a controller as follows:

```rb
ActionController::Base.new.tap do |c|
  request  = ActionDispatch::Request.new({})
  response = ActionDispatch::Response.new

  request.controller_instance = c
  response.request = request

  c.instance_variable_set "@_request", request
  c.instance_variable_set "@_env", request.env
  c.instance_variable_set "@_response", response
end
```

Render a component that defines its template using a `call` method.

### Expected behavior

The component should render (subject to the HTML escaping).

### Actual behavior

This error is raised:

```
ActionView::Template::Error:
        Missing rack.input
```

**Backtrace**:

```
"/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/request.rb:442:in `POST'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.8/lib/action_dispatch/http/request.rb:390:in `block (2 levels) in POST'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.8/lib/action_dispatch/http/parameters.rb:88:in `parse_formatted_parameters'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.8/lib/action_dispatch/http/request.rb:389:in `block in POST'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/request.rb:69:in `fetch'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/request.rb:69:in `fetch_header'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.8/lib/action_dispatch/http/request.rb:388:in `POST'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.8/lib/action_dispatch/http/parameters.rb:55:in `parameters'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.8/lib/action_dispatch/http/mime_negotiation.rb:176:in `params_readable?'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.8/lib/action_dispatch/http/mime_negotiation.rb:81:in `block in formats'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/request.rb:69:in `fetch'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/request.rb:69:in `fetch_header'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.8/lib/action_dispatch/http/mime_negotiation.rb:80:in `formats'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.8/lib/action_dispatch/http/mime_negotiation.rb:76:in `format'",
 "/Users/simonfish/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/view_component-3.9.0/lib/view_component/base.rb:311:in `maybe_escape_html'"
```

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**Gem version**: 3.9.0

**Comment by boardfish** [comment]
I'd fix this myself if I was sure of the way forward, but I'm not sure whether or not this is a concern of the framework. Should we assume all requests have a format and the example I've given is misconfigured, or should we work under the opposite assumption?

**Comment by reeganviljoen** [comment]
@boardfish I think html escaping a component when their is no format is problematic but it is also bad to let it just error, maybe we can render the component without escaping and throw a warning (component could not be escaped because request type was not known ?)

**Comment by boardfish** [comment]
I'm not sure how likely it is that folks will run into this, so I'm less sure about adding a friendly error here this time. I think what I'm looking at (in the reproduction steps) is legacy code and that folks probably wouldn't/shouldn't do things in this way now.

I guess I'm _almost_ answering my own question there – correct use of the framework would probably mean that any request does assume a format, I think, but I'd feel more comfortable with some agreement.

**Comment by boardfish** [comment]
I think I'll close this under the assumption that this probably isn't an intended use of Rails.
