### ISSUE TITLE
Coexistence issues with `active_scaffold` gem

### ISSUE THREAD

**Issue by juankiz** [ViewComponent/view_component#2032]
My best guess is that something similar to either [this issue](https://github.com/ViewComponent/view_component/issues/1945) or [this issue](https://github.com/ViewComponent/view_component/issues/288) that is clashing with [this file](https://github.com/activescaffold/active_scaffold/blob/master/lib/active_scaffold/extensions/action_view_rendering.rb) on active_scaffold but since I'm using rails 7.0 I cant use the `render_component` method.  
I would stick to just add the `render_component` method back directly on my application code, but since it'll be removed in the future, I'm not sure what's the best way to move forward with this.

### Steps to reproduce
On a working Rails + ViewComponent app, add the `active_scaffold` gem.
You can view a minimal example on [this repo](https://github.com/juankiz/view_component_active_scaffold_coexistence)

### Expected behavior
- Rendering the view component should work as intended. 

### Actual behavior
An exception is thown:
```
'#<HelloWorldComponent:0x00000001209635e0 @_routes=nil>' is not an ActiveModel-compatible object. It must implement :to_partial_path.
```

**Backtrace**:
```
actionview (7.0.8.3) lib/action_view/renderer/abstract_renderer.rb:82:in `partial_path'
actionview (7.0.8.3) lib/action_view/renderer/object_renderer.rb:20:in `render_object_derive_partial'
actionview (7.0.8.3) lib/action_view/renderer/renderer.rb:94:in `render_partial_to_object'
actionview (7.0.8.3) lib/action_view/renderer/renderer.rb:53:in `render_partial'
active_scaffold (3.7.4) lib/active_scaffold/extensions/action_view_rendering.rb:200:in `render'
active_scaffold (3.7.4) lib/active_scaffold/extensions/action_view_rendering.rb:69:in `render'
app/views/home/index.html.erb:1
```
### System configuration
**Rails version**:
7.0.8.3

**Ruby version**:
3.3.1

**Gem version**:
3.12.1

**Comment by reeganviljoen** [comment]
@juankiz thank you fir the report

I don't know exactly what may have caused this and how to fix it, but if I have some time to investigate this I will let you know what I fin

Also @joelhawksley @camertron wgay do you think

**Comment by joelhawksley** [comment]
@juankiz I'd love for us to find a way for ViewComponent to not conflict with `active_scaffold`. Might you be up for writing a PR with a failing test and see if you can come up with a fix?

**Comment by planetmcd** [comment]
Hey @joelhawksley, long time no see.  I hope all is well.  

I just stumbled upon this bug too.  I'm looking to dump ActiveScaffold, so will just do that before I introduce ViewComponents.  Just chiming in as a second example.

**Comment by joelhawksley** [comment]
Oh hey @planetmcd! I still say `not in my parish` because of you 😂 

Thanks for the corroborating report ❤

**Comment by planetmcd** [comment]
Love that.  Thanks for spearheading this library!

**Comment by joelhawksley** [comment]
I've validated that this is still an issue even in our latest release. As we do not use `active_scaffold` at GitHub I'm unable to work on adding support for ViewComponent to its monkey patch. If someone would like to do so, I'd happily accept a compatibility test in this repository.
